// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HttpLog struct {
	ID           int32
	Host         pgtype.Text
	LatencyAvgMs pgtype.Int4
	HttpCount    pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type PingLog struct {
	ID              int32
	Host            pgtype.Text
	LatencyAvgMs    pgtype.Int4
	LossRatePercent pgtype.Int4
	PingCount       pgtype.Int4
	CreatedAt       pgtype.Timestamptz
}
